/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedOrgSlugRouteImport } from './routes/_authenticated/$orgSlug'
import { Route as AuthSignupRouteImport } from './routes/_auth/signup'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedInvitationAcceptRouteImport } from './routes/_authenticated/invitation.accept'
import { Route as AuthenticatedOrgSlugTemplatesRouteImport } from './routes/_authenticated/$orgSlug/templates'
import { Route as AuthenticatedOrgSlugSettingsRouteImport } from './routes/_authenticated/$orgSlug/settings'
import { Route as AuthenticatedOrgSlugHelpRouteImport } from './routes/_authenticated/$orgSlug/help'
import { Route as AuthenticatedOrgSlugExercisesRouteImport } from './routes/_authenticated/$orgSlug/exercises'
import { Route as AuthenticatedOrgSlugDashboardRouteImport } from './routes/_authenticated/$orgSlug/dashboard'
import { Route as AuthenticatedOrgSlugSettingsIndexRouteImport } from './routes/_authenticated/$orgSlug/settings/index'
import { Route as AuthenticatedOrgSlugProgramsIndexRouteImport } from './routes/_authenticated/$orgSlug/programs/index'
import { Route as AuthenticatedOrgSlugAthletesIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/index'
import { Route as AuthenticatedOrgSlugSettingsTeamRouteImport } from './routes/_authenticated/$orgSlug/settings/team'
import { Route as AuthenticatedOrgSlugSettingsProfileRouteImport } from './routes/_authenticated/$orgSlug/settings/profile'
import { Route as AuthenticatedOrgSlugSettingsGeneralRouteImport } from './routes/_authenticated/$orgSlug/settings/general'
import { Route as AuthenticatedOrgSlugProgramsNewRouteImport } from './routes/_authenticated/$orgSlug/programs/new'
import { Route as AuthenticatedOrgSlugProgramsProgramIdRouteImport } from './routes/_authenticated/$orgSlug/programs/$programId'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/index'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/logs/index'
import { Route as AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport } from './routes/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOrgSlugRoute = AuthenticatedOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedInvitationAcceptRoute =
  AuthenticatedInvitationAcceptRouteImport.update({
    id: '/invitation/accept',
    path: '/invitation/accept',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrgSlugTemplatesRoute =
  AuthenticatedOrgSlugTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsRoute =
  AuthenticatedOrgSlugSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugHelpRoute =
  AuthenticatedOrgSlugHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugExercisesRoute =
  AuthenticatedOrgSlugExercisesRouteImport.update({
    id: '/exercises',
    path: '/exercises',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugDashboardRoute =
  AuthenticatedOrgSlugDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsIndexRoute =
  AuthenticatedOrgSlugSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRoute,
  } as any)
const AuthenticatedOrgSlugProgramsIndexRoute =
  AuthenticatedOrgSlugProgramsIndexRouteImport.update({
    id: '/programs/',
    path: '/programs/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesIndexRoute =
  AuthenticatedOrgSlugAthletesIndexRouteImport.update({
    id: '/athletes/',
    path: '/athletes/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugSettingsTeamRoute =
  AuthenticatedOrgSlugSettingsTeamRouteImport.update({
    id: '/team',
    path: '/team',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRoute,
  } as any)
const AuthenticatedOrgSlugSettingsProfileRoute =
  AuthenticatedOrgSlugSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRoute,
  } as any)
const AuthenticatedOrgSlugSettingsGeneralRoute =
  AuthenticatedOrgSlugSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOrgSlugSettingsRoute,
  } as any)
const AuthenticatedOrgSlugProgramsNewRoute =
  AuthenticatedOrgSlugProgramsNewRouteImport.update({
    id: '/programs/new',
    path: '/programs/new',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugProgramsProgramIdRoute =
  AuthenticatedOrgSlugProgramsProgramIdRouteImport.update({
    id: '/programs/$programId',
    path: '/programs/$programId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdIndexRoute =
  AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport.update({
    id: '/athletes/$athleteId/',
    path: '/athletes/$athleteId/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute =
  AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport.update({
    id: '/athletes/$athleteId/logs/',
    path: '/athletes/$athleteId/logs/',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)
const AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute =
  AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport.update({
    id: '/athletes/$athleteId/log/$sessionId',
    path: '/athletes/$athleteId/log/$sessionId',
    getParentRoute: () => AuthenticatedOrgSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/$orgSlug/help': typeof AuthenticatedOrgSlugHelpRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsRouteWithChildren
  '/$orgSlug/templates': typeof AuthenticatedOrgSlugTemplatesRoute
  '/invitation/accept': typeof AuthenticatedInvitationAcceptRoute
  '/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/$orgSlug/settings/general': typeof AuthenticatedOrgSlugSettingsGeneralRoute
  '/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/settings/team': typeof AuthenticatedOrgSlugSettingsTeamRoute
  '/$orgSlug/athletes/': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/$orgSlug/programs/': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/athletes/$athleteId/': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/$orgSlug/athletes/$athleteId/logs/': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/login': typeof AuthLoginRoute
  '/signup': typeof AuthSignupRoute
  '/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/$orgSlug/help': typeof AuthenticatedOrgSlugHelpRoute
  '/$orgSlug/templates': typeof AuthenticatedOrgSlugTemplatesRoute
  '/invitation/accept': typeof AuthenticatedInvitationAcceptRoute
  '/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/$orgSlug/settings/general': typeof AuthenticatedOrgSlugSettingsGeneralRoute
  '/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/$orgSlug/settings/team': typeof AuthenticatedOrgSlugSettingsTeamRoute
  '/$orgSlug/athletes': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/$orgSlug/programs': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/$orgSlug/athletes/$athleteId': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/$orgSlug/athletes/$athleteId/logs': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/signup': typeof AuthSignupRoute
  '/_authenticated/$orgSlug': typeof AuthenticatedOrgSlugRouteWithChildren
  '/_authenticated/$orgSlug/dashboard': typeof AuthenticatedOrgSlugDashboardRoute
  '/_authenticated/$orgSlug/exercises': typeof AuthenticatedOrgSlugExercisesRoute
  '/_authenticated/$orgSlug/help': typeof AuthenticatedOrgSlugHelpRoute
  '/_authenticated/$orgSlug/settings': typeof AuthenticatedOrgSlugSettingsRouteWithChildren
  '/_authenticated/$orgSlug/templates': typeof AuthenticatedOrgSlugTemplatesRoute
  '/_authenticated/invitation/accept': typeof AuthenticatedInvitationAcceptRoute
  '/_authenticated/$orgSlug/programs/$programId': typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  '/_authenticated/$orgSlug/programs/new': typeof AuthenticatedOrgSlugProgramsNewRoute
  '/_authenticated/$orgSlug/settings/general': typeof AuthenticatedOrgSlugSettingsGeneralRoute
  '/_authenticated/$orgSlug/settings/profile': typeof AuthenticatedOrgSlugSettingsProfileRoute
  '/_authenticated/$orgSlug/settings/team': typeof AuthenticatedOrgSlugSettingsTeamRoute
  '/_authenticated/$orgSlug/athletes/': typeof AuthenticatedOrgSlugAthletesIndexRoute
  '/_authenticated/$orgSlug/programs/': typeof AuthenticatedOrgSlugProgramsIndexRoute
  '/_authenticated/$orgSlug/settings/': typeof AuthenticatedOrgSlugSettingsIndexRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/': typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId': typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  '/_authenticated/$orgSlug/athletes/$athleteId/logs/': typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
    | '/$orgSlug/help'
    | '/$orgSlug/settings'
    | '/$orgSlug/templates'
    | '/invitation/accept'
    | '/$orgSlug/programs/$programId'
    | '/$orgSlug/programs/new'
    | '/$orgSlug/settings/general'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/settings/team'
    | '/$orgSlug/athletes/'
    | '/$orgSlug/programs/'
    | '/$orgSlug/settings/'
    | '/$orgSlug/athletes/$athleteId/'
    | '/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/$orgSlug/athletes/$athleteId/logs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/login'
    | '/signup'
    | '/$orgSlug'
    | '/$orgSlug/dashboard'
    | '/$orgSlug/exercises'
    | '/$orgSlug/help'
    | '/$orgSlug/templates'
    | '/invitation/accept'
    | '/$orgSlug/programs/$programId'
    | '/$orgSlug/programs/new'
    | '/$orgSlug/settings/general'
    | '/$orgSlug/settings/profile'
    | '/$orgSlug/settings/team'
    | '/$orgSlug/athletes'
    | '/$orgSlug/programs'
    | '/$orgSlug/settings'
    | '/$orgSlug/athletes/$athleteId'
    | '/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/$orgSlug/athletes/$athleteId/logs'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/onboarding'
    | '/_auth/login'
    | '/_auth/signup'
    | '/_authenticated/$orgSlug'
    | '/_authenticated/$orgSlug/dashboard'
    | '/_authenticated/$orgSlug/exercises'
    | '/_authenticated/$orgSlug/help'
    | '/_authenticated/$orgSlug/settings'
    | '/_authenticated/$orgSlug/templates'
    | '/_authenticated/invitation/accept'
    | '/_authenticated/$orgSlug/programs/$programId'
    | '/_authenticated/$orgSlug/programs/new'
    | '/_authenticated/$orgSlug/settings/general'
    | '/_authenticated/$orgSlug/settings/profile'
    | '/_authenticated/$orgSlug/settings/team'
    | '/_authenticated/$orgSlug/athletes/'
    | '/_authenticated/$orgSlug/programs/'
    | '/_authenticated/$orgSlug/settings/'
    | '/_authenticated/$orgSlug/athletes/$athleteId/'
    | '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'
    | '/_authenticated/$orgSlug/athletes/$athleteId/logs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$orgSlug': {
      id: '/_authenticated/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof AuthenticatedOrgSlugRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/signup': {
      id: '/_auth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/invitation/accept': {
      id: '/_authenticated/invitation/accept'
      path: '/invitation/accept'
      fullPath: '/invitation/accept'
      preLoaderRoute: typeof AuthenticatedInvitationAcceptRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$orgSlug/templates': {
      id: '/_authenticated/$orgSlug/templates'
      path: '/templates'
      fullPath: '/$orgSlug/templates'
      preLoaderRoute: typeof AuthenticatedOrgSlugTemplatesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings': {
      id: '/_authenticated/$orgSlug/settings'
      path: '/settings'
      fullPath: '/$orgSlug/settings'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/help': {
      id: '/_authenticated/$orgSlug/help'
      path: '/help'
      fullPath: '/$orgSlug/help'
      preLoaderRoute: typeof AuthenticatedOrgSlugHelpRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/exercises': {
      id: '/_authenticated/$orgSlug/exercises'
      path: '/exercises'
      fullPath: '/$orgSlug/exercises'
      preLoaderRoute: typeof AuthenticatedOrgSlugExercisesRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/dashboard': {
      id: '/_authenticated/$orgSlug/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/dashboard'
      preLoaderRoute: typeof AuthenticatedOrgSlugDashboardRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings/': {
      id: '/_authenticated/$orgSlug/settings/'
      path: '/'
      fullPath: '/$orgSlug/settings/'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRoute
    }
    '/_authenticated/$orgSlug/programs/': {
      id: '/_authenticated/$orgSlug/programs/'
      path: '/programs'
      fullPath: '/$orgSlug/programs/'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/': {
      id: '/_authenticated/$orgSlug/athletes/'
      path: '/athletes'
      fullPath: '/$orgSlug/athletes/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/settings/team': {
      id: '/_authenticated/$orgSlug/settings/team'
      path: '/team'
      fullPath: '/$orgSlug/settings/team'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsTeamRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRoute
    }
    '/_authenticated/$orgSlug/settings/profile': {
      id: '/_authenticated/$orgSlug/settings/profile'
      path: '/profile'
      fullPath: '/$orgSlug/settings/profile'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsProfileRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRoute
    }
    '/_authenticated/$orgSlug/settings/general': {
      id: '/_authenticated/$orgSlug/settings/general'
      path: '/general'
      fullPath: '/$orgSlug/settings/general'
      preLoaderRoute: typeof AuthenticatedOrgSlugSettingsGeneralRouteImport
      parentRoute: typeof AuthenticatedOrgSlugSettingsRoute
    }
    '/_authenticated/$orgSlug/programs/new': {
      id: '/_authenticated/$orgSlug/programs/new'
      path: '/programs/new'
      fullPath: '/$orgSlug/programs/new'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsNewRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/programs/$programId': {
      id: '/_authenticated/$orgSlug/programs/$programId'
      path: '/programs/$programId'
      fullPath: '/$orgSlug/programs/$programId'
      preLoaderRoute: typeof AuthenticatedOrgSlugProgramsProgramIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/'
      path: '/athletes/$athleteId'
      fullPath: '/$orgSlug/athletes/$athleteId/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/logs/': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/logs/'
      path: '/athletes/$athleteId/logs'
      fullPath: '/$orgSlug/athletes/$athleteId/logs/'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
    '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId': {
      id: '/_authenticated/$orgSlug/athletes/$athleteId/log/$sessionId'
      path: '/athletes/$athleteId/log/$sessionId'
      fullPath: '/$orgSlug/athletes/$athleteId/log/$sessionId'
      preLoaderRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRouteImport
      parentRoute: typeof AuthenticatedOrgSlugRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedOrgSlugSettingsRouteChildren {
  AuthenticatedOrgSlugSettingsGeneralRoute: typeof AuthenticatedOrgSlugSettingsGeneralRoute
  AuthenticatedOrgSlugSettingsProfileRoute: typeof AuthenticatedOrgSlugSettingsProfileRoute
  AuthenticatedOrgSlugSettingsTeamRoute: typeof AuthenticatedOrgSlugSettingsTeamRoute
  AuthenticatedOrgSlugSettingsIndexRoute: typeof AuthenticatedOrgSlugSettingsIndexRoute
}

const AuthenticatedOrgSlugSettingsRouteChildren: AuthenticatedOrgSlugSettingsRouteChildren =
  {
    AuthenticatedOrgSlugSettingsGeneralRoute:
      AuthenticatedOrgSlugSettingsGeneralRoute,
    AuthenticatedOrgSlugSettingsProfileRoute:
      AuthenticatedOrgSlugSettingsProfileRoute,
    AuthenticatedOrgSlugSettingsTeamRoute:
      AuthenticatedOrgSlugSettingsTeamRoute,
    AuthenticatedOrgSlugSettingsIndexRoute:
      AuthenticatedOrgSlugSettingsIndexRoute,
  }

const AuthenticatedOrgSlugSettingsRouteWithChildren =
  AuthenticatedOrgSlugSettingsRoute._addFileChildren(
    AuthenticatedOrgSlugSettingsRouteChildren,
  )

interface AuthenticatedOrgSlugRouteChildren {
  AuthenticatedOrgSlugDashboardRoute: typeof AuthenticatedOrgSlugDashboardRoute
  AuthenticatedOrgSlugExercisesRoute: typeof AuthenticatedOrgSlugExercisesRoute
  AuthenticatedOrgSlugHelpRoute: typeof AuthenticatedOrgSlugHelpRoute
  AuthenticatedOrgSlugSettingsRoute: typeof AuthenticatedOrgSlugSettingsRouteWithChildren
  AuthenticatedOrgSlugTemplatesRoute: typeof AuthenticatedOrgSlugTemplatesRoute
  AuthenticatedOrgSlugProgramsProgramIdRoute: typeof AuthenticatedOrgSlugProgramsProgramIdRoute
  AuthenticatedOrgSlugProgramsNewRoute: typeof AuthenticatedOrgSlugProgramsNewRoute
  AuthenticatedOrgSlugAthletesIndexRoute: typeof AuthenticatedOrgSlugAthletesIndexRoute
  AuthenticatedOrgSlugProgramsIndexRoute: typeof AuthenticatedOrgSlugProgramsIndexRoute
  AuthenticatedOrgSlugAthletesAthleteIdIndexRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdIndexRoute
  AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute
  AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute: typeof AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute
}

const AuthenticatedOrgSlugRouteChildren: AuthenticatedOrgSlugRouteChildren = {
  AuthenticatedOrgSlugDashboardRoute: AuthenticatedOrgSlugDashboardRoute,
  AuthenticatedOrgSlugExercisesRoute: AuthenticatedOrgSlugExercisesRoute,
  AuthenticatedOrgSlugHelpRoute: AuthenticatedOrgSlugHelpRoute,
  AuthenticatedOrgSlugSettingsRoute:
    AuthenticatedOrgSlugSettingsRouteWithChildren,
  AuthenticatedOrgSlugTemplatesRoute: AuthenticatedOrgSlugTemplatesRoute,
  AuthenticatedOrgSlugProgramsProgramIdRoute:
    AuthenticatedOrgSlugProgramsProgramIdRoute,
  AuthenticatedOrgSlugProgramsNewRoute: AuthenticatedOrgSlugProgramsNewRoute,
  AuthenticatedOrgSlugAthletesIndexRoute:
    AuthenticatedOrgSlugAthletesIndexRoute,
  AuthenticatedOrgSlugProgramsIndexRoute:
    AuthenticatedOrgSlugProgramsIndexRoute,
  AuthenticatedOrgSlugAthletesAthleteIdIndexRoute:
    AuthenticatedOrgSlugAthletesAthleteIdIndexRoute,
  AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute:
    AuthenticatedOrgSlugAthletesAthleteIdLogSessionIdRoute,
  AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute:
    AuthenticatedOrgSlugAthletesAthleteIdLogsIndexRoute,
}

const AuthenticatedOrgSlugRouteWithChildren =
  AuthenticatedOrgSlugRoute._addFileChildren(AuthenticatedOrgSlugRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedOrgSlugRoute: typeof AuthenticatedOrgSlugRouteWithChildren
  AuthenticatedInvitationAcceptRoute: typeof AuthenticatedInvitationAcceptRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOrgSlugRoute: AuthenticatedOrgSlugRouteWithChildren,
  AuthenticatedInvitationAcceptRoute: AuthenticatedInvitationAcceptRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
